### ISSUE TITLE
Consuming high amounts of memory?

### ISSUE THREAD

**Issue by nathanielks** [aws/aws-xray-daemon#11]
Hiya, team!

We're running the daemon on our servers and are seeing extraordinarily high memory usage. I'm currently seeing one server with 20% (800M), and I've seen other servers with 50% (I don't recall if that was a 2G or 4G instance, but either way: 1-2G of memory consumed).

We're running the default configuration:
```
# Maximum buffer size in MB (minimum 3). Choose 0 to use 1% of host memory.
TotalBufferSizeMB: 0
# Maximum number of concurrent calls to AWS X-Ray to upload segment documents.
Concurrency: 8
# Send segments to AWS X-Ray service in a specific region
Region: ""
# Change the X-Ray service endpoint to which the daemon sends segment documents.
Endpoint: ""
Socket:
  # Change the address and port on which the daemon listens for UDP packets containing segment documents.
  UDPAddress: "127.0.0.1:2000"
Logging:
  LogRotation: true
  # Change the log level, from most verbose to least: dev, debug, info, warn, error, prod (default).
  LogLevel: "prod"
  # Output logs to the specified file path.
  LogPath: ""
# Turn on local mode to skip EC2 instance metadata check.
LocalMode: false
# Amazon Resource Name (ARN) of the AWS resource running the daemon.
ResourceARN: ""
# Assume an IAM role to upload segments to a different account.
RoleARN: ""
# Disable TLS certificate verification.
NoVerifySSL: false
# Upload segments to AWS X-Ray through a proxy.
ProxyAddress: ""
# Daemon configuration file format version.
```

I'm unsure of how to debug this. Any ideas?
