### ISSUE TITLE
X-Ray daemon not sending traces to X-Ray service

### ISSUE THREAD

**Issue by MatteoGioioso** [aws/aws-xray-daemon#43]
I am trying to run a the x-ray daemon inside a docker container

this is my `docker-compose.yaml`

```
version: '3'

services:
//Other services

  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:8080
    links:
      - redis
    depends_on:
      - db
    command:
      sh -c 'npm i && npm run start'

  xray:
    build:
      context: ./
      dockerfile: Dockerfile.xray
    ports:
    - 2000:2000/udp
    - 2000:2000/tcp
    environment:
      - AWS_REGION=ap-southeast-1

```

Docker file for the xray image

```
FROM amazonlinux
RUN yum install -y unzip
RUN curl -o daemon.zip https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
RUN unzip daemon.zip && cp xray /usr/bin/xray
ENTRYPOINT ["/usr/bin/xray", "-t", "0.0.0.0:2000", "-b", "0.0.0.0:2000"]
EXPOSE 2000/udp
EXPOSE 2000/tcp
```

my instrumented nodejs app
```
const AWSXRay = require('aws-xray-sdk')
app.use(AWSXRay.express.openSegment('my-backend'))
// all the routes here
// ...

app.use(AWSXRay.express.closeSegment())
```

Those are the docker-compose logs

```
xray_1   | 2020-03-03T06:16:28Z [Info] Initializing AWS X-Ray daemon 3.2.0
xray_1   | 2020-03-03T06:16:28Z [Info] Using buffer memory limit of 9 MB
xray_1   | 2020-03-03T06:16:28Z [Info] 144 segment buffers allocated
xray_1   | 2020-03-03T06:16:28Z [Info] Using region: ap-southeast-1

xray_1   | 2020-03-03T06:30:27Z [Info] HTTP Proxy server using X-Ray Endpoint : https://xray.ap-southeast-1.amazonaws.com
xray_1   | 2020-03-03T06:30:27Z [Info] Starting proxy http server on 0.0.0.0:2000

```

I have a IAM role attached to my EC2 with `AWSXrayFullAccess` policy.

Obviously I am sending a bunch of requests, but still I do not see anything anything in the X-Ray console as well as the  `[Info] Successfully sent batch of 1 segments` in the docker-compose logs

Any idea?
Thanks

**EDIT:**
I have tried to send manually a segment with ` cat segment.txt > /dev/udp/127.0.0.1/2000
` and it worked

```
xray_1   | 2020-03-03T09:22:52Z [Info] Successfully sent batch of 1 segments (0.020 seconds)
```

So I must have done something wrong with the SDK
