### ISSUE TITLE
Cannot start the x-ray daemon on Elastic Beanstalk host.

### ISSUE THREAD

**Issue by jmrr** [aws/aws-xray-daemon#50]
I'm running a Single Docker Elastic Beanstalk environment. I'm trying to run the X-Ray daemon by setting the following configuration
```
commands:
  01-stop-tracing:
    command: yum remove -y xray
    ignoreErrors: true
  02-copy-tracing:
    command: curl https://s3.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
  03-start-tracing:
    command: yum install -y /home/ec2-user/xray.rpm

files:
  "/opt/elasticbeanstalk/tasks/taillogs.d/xray-daemon.conf" :
    mode: "000644"
    owner: root
    group: root
    content: |
      /var/log/xray/xray.log
  "/etc/amazon/xray/cfg.yaml" :
    mode: "000644"
    owner: root
    group: root
    content: |
      Logging:
        LogLevel: "debug"
```

However, this is what I see in the logs:

```
[Error] Config Version Setting is not correct. Use X-Ray Daemon Config Migration Script to update the config file. Please refer to AWS X-Ray Documentation for more information.
```

I've also tried using the manual binary with the default `cfg.yaml` and surprise surprise, works **inside** the container but not outside, in the Beanstalk host. 

What am I doing wrong? I've tried looking the error up on Google to no avail.
