### ISSUE TITLE
Add health endpoint

### ISSUE THREAD

**Issue by Mortinke** [aws/aws-xray-daemon#9]
Referring to the [pinging the xray daemon ](https://forums.aws.amazon.com/thread.jspa?threadID=282144&tstart=0) forum post, it would be nice, if a health endpoint could be added for the X-Ray daemon. 

Currently, we use a crontab bash script in the ECS launch configuration to check the status of the X-Ray daemon. Instead, we would like to use a health endpoint.

**Comment by yogiraj07** [comment]
Hi @Mortinke ,
We appreciate your feature request. I would add this to our backlog item. We also welcome you to submit PR. Thanks for patience and stay tuned. 

Best,
Yogi

**Comment by jason-riddle** [comment]
In addition to the great answer from @Sweathered's stack overflow post, I've been instead doing the following. I have the following in my docker-compose.yml.

`docker-compose.yml`

```yml
version: '3.5'

x-global: &global
  AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
  AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  AWS_REGION: us-east-1

services:
  xray:
    image: amazon/aws-xray-daemon
    command: --config /xray-daemon.yml
    hostname: xray
    environment:
      <<: *global
    ports:
      - 2000:2000/udp
    volumes:
      - ./integration/xray/xray-daemon.yml:/xray-daemon.yml:ro
    healthcheck:
      test: timeout 1 /bin/bash -c '</dev/tcp/localhost/2000 && </dev/udp/localhost/2000'
      interval: 2s
      timeout: 2s
      retries: 1
```

I'm relying on bash native features (timeout built-in, opening tcp/udp socket capability) to do the health check. Compared to the solution from stackoverflow

```
CMD-SHELL, netstat -aun | grep 2000 > /dev/null; if [ 0 != $? ]; then exit 1; fi;
```

I'd rather not have to depend on netstat and grep being available, having to pipe, and write a single line if statement. However, it would be better if the xray daemon supported this naturally through maybe a `/ready` or `/healthz` endpoint because even though you can connect to the tcp/udp socket, that does not necessarily mean everything is functioning as expected since there may be some internal issue going on (running low on space, high number of goroutines running, connectivity issue to AWS, etc).
